# Generated by Django 5.2.8 on 2026-06-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('current_school', models.CharField(max_length=300)),
                ('level', models.CharField(choices=[('primary', 'Shule ya Msingi'), ('secondary', 'Shule ya Sekondari')], max_length=20)),
                ('subjects', models.CharField(blank=True, help_text='Masomo yanayofundishwa, e.g. Hisabati, Fizikia', max_length=500)),
                ('region_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('village', 'Kijijini'), ('middle', 'Mji Mdogo'), ('urban', 'Mjini')], max_length=20)),
                ('willing_to_go', models.CharField(blank=True, choices=[('village', 'Kijijini'), ('middle', 'Mji Mdogo'), ('urban', 'Mjini')], help_text='Aina ya eneo anayotaka kwenda', max_length=20)),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
