# Re-export every name from the old views.py so existing imports keep working.

from .utils import (
    _cached_active_year,
    _cached_subjects,
    _cached_today_logbook,
    _invalidate_today_logbook,
    _cached_schools_by_district,
    _cached_all_districts,
    _cached_all_regions,
    get_assessor_email_template,
    process_bulk_assignment_with_academic_year,
    get_or_create_student_profile,
    invalidate_student_cache,
    is_assessor,
    generate_random_password,
    get_current_academic_year,
    _build_individual_letter_pdf,
    _active_year_students,
    _get_board_member,
    _can_access_region,
    _can_access_district,
    _normalize_school_code,
    _ai_parse_allocation_document,
    _generate_requests_pdf,
    _send_sms_africastalking,
    _ai_summarise_requests,
    _get_deo_for_district,
)

from .auth import (
    health_check,
    session_check,
    register,
    login_view,
    logout_view,
    login_page,
    login_page_simple,
    homepage,
    set_language,
)

from .student import (
    dashboard,
    student_monthly_report,
    select_region,
    select_district,
    select_school,
    search_schools_ajax,
    select_subjects,
    apply_for_subject,
    submit_logbook,
    logbook_history,
    download_logbook_pdf,
    logbook_download_options,
    profile_create,
    get_subjects,
    confirm_school_selection,
    my_assessors,
    change_school,
    student_certificate,
    student_certificate_pdf,
    student_confirmation_letter_pdf,
)

from .assessor import (
    assessor_login,
    assessor_dashboard,
    assessor_password_reset,
    assessor_password_reset_done,
    assessor_student_detail,
    assessor_student_assessment,
    assessor_add_logbook_remark,
    assessor_list,
)

from .board import (
    head_teacher_login,
    board_login,
    board_logout,
    board_home,
    board_district_list,
    board_school_list,
    board_student_progress,
    board_add_comment,
    board_head_teacher,
    board_final_assessment,
    board_deo_report,
    deo_approve_district_certificates,
    head_teacher_monthly_report,
    final_assessment_pdf,
    deo_allocation,
    deo_district_allocation,
    deo_review_requests,
    deo_student_pdf,
    send_links_to_heads,
)

from .admin_views import (
    help_page,
    admin_dashboard,
    approve_application,
    download_backup,
    assign_assessor,
    bulk_assign_assessors,
    bulk_assignment_results,
    student_list,
    approve_student,
    manage_regions,
    toggle_region_pin,
    reset_all_region_pins,
    region_pinning_view,
    pinning_success_view,
    change_academic_year,
    create_academic_year,
    create_admin,
    admin_report_pdf,
    import_head_teachers,
    create_board_member,
    reset_assessors_for_new_year,
    new_year_credentials,
    download_individual_letter,
    download_group_letter,
    send_test_email_api,
)

from .api import (
    ajax_search_schools,
    assessor_details_api,
    api_confirm_change_school,
    api_get_schools_for_change,
    get_classes_by_level,
    get_subjects_by_level,
    get_textbooks_by_level,
    api_get_schools,
    api_select_school_temp,
    api_districts_by_region,
    api_clear_selected_school,
    api_filter_schools,
)

from .schemes import (
    generate_scheme_view,
    ajax_generate_scheme,
    ajax_load_saved_scheme,
    download_scheme_pdf,
    download_scheme_word,
    download_lesson_plan_pdf,
    download_lesson_plan_word,
    lesson_plan_view,
    ajax_generate_lessonplan,
    ajax_load_saved_lessonplan,
)

from .public import (
    public_school_head_form,
    school_head_submit,
)

from .assistant import (
    application_assistant,
    application_chat_stream,
    application_confirm,
    application_edit_field,
    application_start_automation,
    application_auto_status,
    heslb_knowledge_status,
)
