# Generated by Django 5.2.8 on 2026-08-11 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jina la Ada/Mchango')),
                ('category', models.CharField(choices=[('ada', 'Ada (Tuition)'), ('mchango', 'Mchango wa Chuo'), ('other', 'Nyingine')], default='ada', max_length=20, verbose_name='Aina')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kiasi (TZS)')),
                ('academic_year', models.CharField(blank=True, help_text='Wacha tupu kwa ada za kila mwaka.', max_length=20, verbose_name='Mwaka wa Masomo')),
                ('year_of_study', models.IntegerField(blank=True, help_text='1 au 2; wacha tupu ikiwa inahusu miaka yote.', null=True, verbose_name='Mwaka wa Masomo unaohusika')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Tarehe ya Malipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inatumika')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_items', to='colleges.college', verbose_name='Chuo')),
            ],
            options={
                'verbose_name': 'Ada / Mchango',
                'verbose_name_plural': 'Ada na Michango',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Mwaka wa Masomo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kiasi (TZS)')),
                ('status', models.CharField(choices=[('unpaid', 'Haijalipwa'), ('partially_paid', 'Imelipwa Sehemu'), ('paid', 'Imelipwa')], default='unpaid', max_length=20)),
                ('control_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Namba ya Malipo (Control Number)')),
                ('control_number_generated_at', models.DateTimeField(blank=True, null=True)),
                ('control_number_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='students.student', verbose_name='Mwanafunzi')),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='fees.feeitem', verbose_name='Ada / Mchango')),
            ],
            options={
                'verbose_name': 'Bili',
                'verbose_name_plural': 'Bili',
                'ordering': ['fee_item__category', 'created_at'],
                'unique_together': {('student', 'fee_item', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kiasi (TZS)')),
                ('method', models.CharField(choices=[('bank', 'Benki (NMB / CRDB / NBC)'), ('mobile', 'Simu ya Mkonomi (M-Pesa / Tigo Pesa / Airtel Money)'), ('cash', 'Fedha Taslimu (Cash)'), ('other', 'Nyingine')], default='mobile', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='mfano: kumbukumbu ya M-Pesa/Tigo, au namba ya benki', max_length=100, verbose_name='Namba ya Kumbukumbu')),
                ('status', models.CharField(choices=[('pending', 'Inasubiri Kuthibitishwa'), ('confirmed', 'Imethibitishwa'), ('rejected', 'Imekataliwa')], default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Maelezo')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.feebill', verbose_name='Bili')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Aliyethibitisha')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Mwanafunzi')),
            ],
            options={
                'verbose_name': 'Malipo',
                'verbose_name_plural': 'Malipo',
                'ordering': ['-created_at'],
            },
        ),
    ]
