# Generated by Django 5.2.8 on 2026-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feebill',
            name='gepg_bill_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='GePG Bill ID'),
        ),
    ]
