# Generated by Django 5.2.8 on 2025-12-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0002_empty'),
        ('field_app', '0004_academic_year_done'),
    ]

    operations = [
    ]
