# Generated by Django 5.2.8 on 2025-12-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0005_merge_0002_empty_0004_academic_year_done'),
    ]

    operations = [
    ]
