# Generated by Django 5.2.8 on 2026-10-09 18:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_app', '0036_lessonplan_format_schemeofwork_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('somo', models.CharField(max_length=100)),
                ('kidato', models.CharField(blank=True, max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=400)),
                ('mode', models.CharField(choices=[('annual', 'Mwaka mzima (100% mwisho wa mwaka)'), ('periods', 'Vipindi kwa wiki (vipindi_kwa_wiki x wiki)'), ('manual', 'Actual / Target')], default='manual', max_length=10)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vila_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('week_count', models.PositiveSmallIntegerField(default=0)),
                ('actual_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='ess_tracker.task')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('task', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('ess_username', models.CharField(blank=True, help_text='Jina au barua pepe unayotumia kuingia ESS (e-Utendaji)', max_length=255)),
                ('ess_password', models.CharField(blank=True, max_length=512)),
                ('ess_ready', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ess_profiles', to='field_app.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ess_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ess_tracker.teacherprofile'),
        ),
        migrations.CreateModel(
            name='EssFillRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Inajaza...'), ('done', 'Imekamilika'), ('error', 'Hitilafu')], default='running', max_length=20)),
                ('saved', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('not_found', models.IntegerField(default=0)),
                ('required', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_runs', to='ess_tracker.teacherprofile')),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='WeekEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.PositiveSmallIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_entries', to='ess_tracker.teacherprofile')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ess_tracker.subtask')),
            ],
            options={
                'ordering': ['week_no'],
                'unique_together': {('subtask', 'week_no')},
            },
        ),
    ]
