# Generated by Django 5.2.8 on 2026-10-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekentry',
            options={'ordering': ['date', 'week_no']},
        ),
        migrations.AlterUniqueTogether(
            name='weekentry',
            unique_together={('subtask', 'date')},
        ),
        migrations.AlterField(
            model_name='weekentry',
            name='week_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
