# Generated by Django 6.0 on 2025-12-31 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolassessment',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problematicschool',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='regionpin',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='schoolassessment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='schoolassessment',
            name='assessment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schoolassessment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schoolpin',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.academicyear'),
        ),
        migrations.CreateModel(
            name='RegionalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.academicyear')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.region')),
            ],
            options={
                'unique_together': {('academic_year', 'region')},
            },
        ),
        migrations.CreateModel(
            name='SchoolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('assessment_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.assessor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.school')),
            ],
            options={
                'unique_together': {('assessor', 'school')},
            },
        ),
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.school')),
            ],
            options={
                'unique_together': {('academic_year', 'school')},
            },
        ),
        migrations.CreateModel(
            name='SchoolSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.school')),
            ],
            options={
                'unique_together': {('academic_year', 'school')},
            },
        ),
    ]
