# Generated by Django 5.2.8 on 2026-04-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0003_fix_schoolassessment_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteacher',
            name='initial_school_selection_date',
            field=models.DateTimeField(blank=True, help_text='Tarehe ya kwanza mwanafunzi alipochagua shule', null=True),
        ),
        migrations.AddField(
            model_name='studentteacher',
            name='last_school_change_date',
            field=models.DateTimeField(blank=True, help_text='Tarehe ya mwisho kubadili shule', null=True),
        ),
        migrations.AddField(
            model_name='studentteacher',
            name='school_change_count',
            field=models.IntegerField(default=0, help_text='Idadi ya mara mwanafunzi amebadili shule'),
        ),
    ]
