# Generated by Django 5.2.8 on 2026-05-22 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0004_studentteacher_initial_school_selection_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('scheme_of_work', 'Scheme of Work'), ('lesson_plan', 'Lesson Plan')], max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict, null=True)),
                ('prompt_sent', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generation_time_ms', models.IntegerField(default=0, help_text='Generation time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.studentteacher')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('ordinary', 'Ordinary Level'), ('advanced', 'Advanced Level')], max_length=20)),
                ('class_name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('I', 'Term I'), ('II', 'Term II'), ('III', 'Term III')], max_length=10)),
                ('year', models.IntegerField(default=2026)),
                ('syllabus', models.CharField(default='New Syllabus', max_length=100)),
                ('total_weeks', models.IntegerField(default=12)),
                ('periods_per_week', models.IntegerField(default=8)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('teacher_name', models.CharField(max_length=200)),
                ('reference_source', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='scheme_references/')),
                ('scheme_data', models.JSONField(default=list, help_text='Generated scheme of work data')),
                ('breaks', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='field_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='field_app.studentteacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='field_app.subject')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
                'unique_together': {('student', 'subject', 'term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('ordinary', 'Ordinary Level'), ('advanced', 'Advanced Level')], max_length=20)),
                ('class_name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('I', 'Term I'), ('II', 'Term II'), ('III', 'Term III')], max_length=10)),
                ('year', models.IntegerField(default=2026)),
                ('topic', models.CharField(max_length=200)),
                ('subtopic', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=40, help_text='Duration in minutes')),
                ('teacher_name', models.CharField(max_length=200)),
                ('council_name', models.CharField(blank=True, max_length=200, null=True)),
                ('region_name', models.CharField(blank=True, max_length=200, null=True)),
                ('office_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_students', models.IntegerField(blank=True, default=0, null=True)),
                ('present_students', models.IntegerField(blank=True, default=0, null=True)),
                ('reference_source', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='lesson_references/')),
                ('main_competence', models.TextField(blank=True, null=True)),
                ('specific_competence', models.TextField(blank=True, null=True)),
                ('previous_knowledge', models.TextField(blank=True, null=True)),
                ('learning_objectives', models.JSONField(default=list, help_text='List of learning objectives')),
                ('teaching_methods', models.JSONField(default=list, help_text='List of teaching methods')),
                ('teaching_resources', models.JSONField(default=list, help_text='List of teaching resources')),
                ('lesson_development', models.JSONField(default=list)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('ai_model_used', models.CharField(blank=True, default='gemini-1.5-flash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logbook_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='field_app.logbookentry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='field_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='field_app.studentteacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='field_app.subject')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='field_app.schemeofwork')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='references/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('scheme', 'Scheme of Work'), ('lesson', 'Lesson Plan'), ('textbook', 'Textbook'), ('syllabus', 'Syllabus'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_references', to='field_app.studentteacher')),
            ],
        ),
    ]
