# Generated by Django 6.0.5 on 2026-05-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0005_aigenerationlog_schemeofwork_lessonplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='field_app.educationlevel')),
            ],
            options={
                'ordering': ['education_level', 'order'],
                'unique_together': {('education_level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('ordinary', 'Ordinary Level'), ('advanced', 'Advanced Level')], max_length=20)),
                ('publisher', models.CharField(default='TIE', max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='textbooks/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='textbook_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.classlevel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.subject')),
            ],
        ),
    ]
