# Generated by Django 5.2.8 on 2026-05-26 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0006_educationlevel_classlevel_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('theory', 'Somo la Nadharia'), ('practical', 'Vitendo/Maabara'), ('revision', 'Mapitio'), ('assessment', 'Tathmini/Mtihani'), ('preparation', 'Maandalizi ya Somo'), ('other', 'Nyingine')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='class_taught',
            field=models.CharField(blank=True, help_text='e.g. Form 2A, Standard 5', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='num_students_present',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='subject_taught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_entries', to='field_app.subject'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='topic_taught',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('inspector', 'Mkaguzi wa Shule'), ('head_teacher', 'Mkuu wa Shule'), ('deo', 'Afisa Elimu wa Wilaya (DEO)'), ('reo', 'Afisa Elimu wa Mkoa (REO)'), ('chair', 'Mwenyekiti wa Bodi'), ('member', 'Mjumbe wa Bodi')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_members', to='field_app.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_members', to='field_app.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('excellent', 'Vizuri Sana — Endelea Hivyo'), ('good', 'Vizuri — Kazi Nzuri'), ('average', 'Wastani — Boresha'), ('behind', 'Nyuma — Akazane'), ('critical', 'Muhimu — Hatua ya Haraka')], default='good', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_comments', to='field_app.studentteacher')),
                ('board_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='field_app.boardmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
