# Generated by Django 5.2.8 on 2026-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0007_logbookentry_activity_type_logbookentry_class_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='head_teacher_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='lessons_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='other_activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='supervisor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
