# Generated by Django 5.2.8 on 2026-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0008_tie_logbook_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boardcomment',
            index=models.Index(fields=['student', '-created_at'], name='field_app_b_student_eb0682_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['student', 'date'], name='field_app_l_student_802745_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['student', '-date'], name='field_app_l_student_e1ddda_idx'),
        ),
    ]
