# Generated by Django 5.2.8 on 2026-05-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0009_db_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Machi'), (4, 'Aprili'), (5, 'Mei'), (6, 'Juni'), (7, 'Julai'), (8, 'Agosti'), (9, 'Septemba'), (10, 'Oktoba'), (11, 'Novemba'), (12, 'Desemba')])),
                ('year', models.PositiveSmallIntegerField()),
                ('ai_content', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='field_app.district')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.boardmember')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['district', 'year', 'month'], name='field_app_m_distric_0b35d1_idx')],
                'unique_together': {('district', 'month', 'year')},
            },
        ),
    ]
