# Generated by Django 6.0.5 on 2026-05-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0010_monthly_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_needed', models.PositiveIntegerField(default=0, help_text='Walimu wanafunzi wa shule za msingi')),
                ('secondary_needed', models.PositiveIntegerField(default=0, help_text='Walimu wanafunzi wa shule za sekondari')),
                ('notes', models.TextField(blank=True, help_text='Maelezo ya ziada kutoka DEO')),
                ('document', models.FileField(blank=True, help_text='Hati ya mahitaji (PDF/Word)', null=True, upload_to='allocations/')),
                ('ai_parsed', models.BooleanField(default=False, help_text='AI ilitumika kuchambua document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_allocations', to='field_app.academicyear')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='field_app.district')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='field_app.boardmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('district', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SchoolAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.PositiveIntegerField(default=0, help_text='Idadi ya walimu wanafunzi wanaohitajika')),
                ('district_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_allocations', to='field_app.districtallocation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='field_app.school')),
            ],
            options={
                'unique_together': {('district_allocation', 'school')},
            },
        ),
    ]
