# Generated by Django 6.0.5 on 2026-05-30 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0011_district_school_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_submitted', models.CharField(help_text='Jina la shule kama ilivyoandikwa na mkuu', max_length=255)),
                ('head_name', models.CharField(max_length=255)),
                ('head_phone', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(choices=[('Primary', 'Shule ya Msingi'), ('Secondary', 'Shule ya Sekondari')], max_length=20)),
                ('students_needed', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('reviewed', 'Imepitiwa na DEO'), ('applied', 'Imewekwa kwenye Allocation'), ('rejected', 'Imekataliwa')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_app.academicyear')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_requests', to='field_app.district')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='field_app.boardmember')),
                ('school', models.ForeignKey(blank=True, help_text='Shule iliyolinganishwa na AI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_requests', to='field_app.school')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
