# Generated by Django 6.0.5 on 2026-05-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0012_school_head_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together={('assessor', 'student', 'school', 'academic_year')},
        ),
    ]
