# Generated by Django 6.0.5 on 2026-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0013_fix_indexes_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='head_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='head_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
