# Generated by Django 6.0.5 on 2026-05-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0014_add_school_head_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Namba ya usajili e.g. S.0123 au P.4567', max_length=20),
        ),
    ]
