# Generated by Django 6.0.5 on 2026-06-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0015_add_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_members', to='field_app.school'),
        ),
    ]
