# Generated by Django 6.0.5 on 2026-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0016_add_school_to_boardmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolallocation',
            name='head_teacher_notes',
            field=models.TextField(blank=True, help_text='Maelezo ya Mkuu wa Shule'),
        ),
        migrations.AddField(
            model_name='schoolallocation',
            name='head_teacher_requested',
            field=models.PositiveIntegerField(default=0, help_text='Idadi iliyoombwa na Mkuu wa Shule'),
        ),
        migrations.AlterField(
            model_name='schoolallocation',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='Idadi iliyoidhinishwa na DEO'),
        ),
    ]
