# Generated by Django 6.0.5 on 2026-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0017_add_ht_fields_to_schoolallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolheadrequest',
            name='submitter_email',
            field=models.EmailField(blank=True, help_text='Email ya mkuu aliyetuma ombi', max_length=254),
        ),
    ]
