# Generated by Django 6.0.5 on 2026-06-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0018_add_submitter_email_to_headrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ownership',
            field=models.CharField(choices=[('government', 'Serikali'), ('private', 'Binafsi')], default='government', help_text='Aina ya umiliki wa shule', max_length=10),
        ),
    ]
