# Generated by Django 5.2.8 on 2026-06-07 11:38

import django.db.models.deletion
from django.db import migrations, models


def populate_academic_year(apps, schema_editor):
    """Set existing students' academic_year to the currently active year."""
    AcademicYear = apps.get_model('field_app', 'AcademicYear')
    StudentTeacher = apps.get_model('field_app', 'StudentTeacher')
    active_year = AcademicYear.objects.filter(is_active=True).first()
    if active_year:
        StudentTeacher.objects.filter(academic_year__isnull=True).update(academic_year=active_year)


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0019_add_school_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteacher',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='field_app.academicyear'),
        ),
        migrations.RunPython(populate_academic_year, migrations.RunPython.noop),
    ]
