# Generated by Django 5.2.8 on 2026-06-07 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0020_add_academic_year_to_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuhudhuria', models.PositiveSmallIntegerField(default=0, help_text='Kuhudhuria (0–20)')),
                ('daftari_la_kazi', models.PositiveSmallIntegerField(default=0, help_text='Daftari la Kazi (0–20)')),
                ('mpango_wa_kazi', models.PositiveSmallIntegerField(default=0, help_text='Mpango wa Kazi (0–20)')),
                ('mpango_wa_somo', models.PositiveSmallIntegerField(default=0, help_text='Mpango wa Somo (0–20)')),
                ('utendaji_darasani', models.PositiveSmallIntegerField(default=0, help_text='Utendaji Darasani (0–20)')),
                ('maoni', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False, help_text='Imekamilishwa — haiwezi kubadilishwa')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.academicyear')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_assessments', to='field_app.boardmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_assessment', to='field_app.studentteacher')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
