# Generated by Django 5.2.8 on 2026-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0021_add_final_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolallocation',
            name='subjects_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Mgawanyo wa masomo: {"Kiswahili": 2, "Mathematics": 4}'),
        ),
        migrations.AddField(
            model_name='schoolheadrequest',
            name='subjects_needed',
            field=models.JSONField(blank=True, default=dict, help_text='Masomo yanayohitajika: {"Kiswahili": 2, "Mathematics": 4}'),
        ),
    ]
