# Generated by Django 5.2.8 on 2026-06-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0025_remove_fake_arusha_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='daftari_la_kazi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Daftari la Kazi (0–20)'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Assessor amekamilisha tathmini'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='kuhudhuria',
            field=models.PositiveSmallIntegerField(default=0, help_text='Kuhudhuria (0–20)'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='mpango_wa_kazi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Mpango wa Kazi (0–20)'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='mpango_wa_somo',
            field=models.PositiveSmallIntegerField(default=0, help_text='Mpango wa Somo (0–20)'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='utendaji_darasani',
            field=models.PositiveSmallIntegerField(default=0, help_text='Utendaji Darasani (0–20)'),
        ),
        migrations.AlterField(
            model_name='finalassessment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='Tarehe mkuu alipokamilisha', null=True),
        ),
    ]
