# Generated by Django 5.2.8 on 2026-06-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0026_assessor_assessment_criteria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='SupervisionVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuhudhuria', models.PositiveSmallIntegerField(default=0)),
                ('daftari_la_kazi', models.PositiveSmallIntegerField(default=0)),
                ('mpango_wa_kazi', models.PositiveSmallIntegerField(default=0)),
                ('mpango_wa_somo', models.PositiveSmallIntegerField(default=0)),
                ('utendaji_darasani', models.PositiveSmallIntegerField(default=0)),
                ('maoni', models.TextField(blank=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.boardmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_visits', to='field_app.studentteacher')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
