# Generated by Django 5.2.8 on 2026-07-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0029_seed_special_needs_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='present_boys',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='present_girls',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='total_boys',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='total_girls',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='field_app.studentteacher'),
        ),
        migrations.AlterField(
            model_name='schemeofwork',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='field_app.studentteacher'),
        ),
    ]
