# Generated by Django 5.2.8 on 2026-07-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0030_make_student_nullable_tlm'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='present_boys',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='present_girls',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='total_boys',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='total_girls',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
