# Generated by Django 5.2.8 on 2026-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0031_lesson_notes_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('advanced', 'Advanced')], default='secondary', max_length=20),
        ),
    ]
