# Generated by Django 5.2.8 on 2026-07-28 06:23

from django.db import migrations


def rename_computer_studies(apps, schema_editor):
    Subject = apps.get_model('field_app', 'Subject')
    Subject.objects.filter(code='S13', name='Computer Studies').update(name='Computer Science')


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0032_add_advanced_subject_level'),
    ]

    operations = [
        migrations.RunPython(rename_computer_studies, migrations.RunPython.noop),
    ]
