# Generated by Django 5.2.8 on 2026-08-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_app', '0035_textbook_technical_level_url_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='format',
            field=models.CharField(choices=[('table', 'Kwa Jedwali (Table)'), ('notable', 'Bila Jedwali (E-Logbook)')], default='table', help_text='table = jedwali la IDDR; notable = mpango wa somo wa E-Logbook (VETA)', max_length=20, verbose_name='Muundo / Format'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='format',
            field=models.CharField(choices=[('table', 'Kwa Jedwali (Table)'), ('notable', 'Bila Jedwali (No Table)')], default='table', help_text='table = jedwali la kawaida; notable = orodha bila jedwali (VETA)', max_length=20, verbose_name='Muundo / Format'),
        ),
    ]
