# Generated by Django 5.2.8 on 2026-07-24 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_app', '0029_seed_special_needs_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLMTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Jina Kamili')),
                ('phone_number', models.CharField(help_text='Namba ya simu itakayotumika kukutambua ukirudi', max_length=15, unique=True, verbose_name='Namba ya Simu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.district', verbose_name='Wilaya')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.region', verbose_name='Mkoa')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.school', verbose_name='Shule')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.subject', verbose_name='Somo')),
            ],
            options={
                'verbose_name': 'Mwalimu (TLM)',
                'verbose_name_plural': 'Walimu (TLM)',
                'ordering': ['-created_at'],
            },
        ),
    ]
