# Generated by Django 5.2.8 on 2026-07-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200, verbose_name='Jina la Mwalimu')),
                ('school_name', models.CharField(blank=True, max_length=300, verbose_name='Jina la Shule')),
                ('message', models.TextField(verbose_name='Ujumbe / Maoni')),
                ('role', models.CharField(blank=True, default='Mwalimu', max_length=100, verbose_name='Wadhifa')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Imeidhinishwa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.tlmteacher', verbose_name='Mwalimu')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
