# Generated by Django 5.2.8 on 2026-07-27 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_testimonial'),
        ('field_app', '0031_lesson_notes_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200, verbose_name='Jina la Mwalimu')),
                ('school_name', models.CharField(blank=True, max_length=300, verbose_name='Jina la Shule')),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('ordinary', 'Ordinary Level'), ('advanced', 'Advanced Level')], default='ordinary', max_length=20, verbose_name='Ngazi ya Elimu')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='Darasa')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Somo')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='Mada / Topic')),
                ('content', models.TextField(verbose_name='Maelezo ya Somo (Lesson Notes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.school', verbose_name='Shule')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.tlmteacher', verbose_name='Mwalimu')),
            ],
            options={
                'verbose_name': 'Lesson Note',
                'verbose_name_plural': 'Lesson Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
