# Generated by Django 5.2.8 on 2026-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_lesson_notes_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmteacher',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Darasa'),
        ),
        migrations.AddField(
            model_name='tlmteacher',
            name='stream',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Stream/Section'),
        ),
        migrations.AddField(
            model_name='tlmteacher',
            name='total_boys',
            field=models.PositiveIntegerField(default=0, verbose_name='Wavulana (Registered)'),
        ),
        migrations.AddField(
            model_name='tlmteacher',
            name='total_girls',
            field=models.PositiveIntegerField(default=0, verbose_name='Wasichana (Registered)'),
        ),
    ]
