# Generated by Django 5.2.8 on 2026-07-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_add_teacher_class_fields'),
        ('field_app', '0033_rename_computer_studies'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='e.g. Form 1, Form 2, Standard 5', max_length=50, verbose_name='Darasa')),
                ('name', models.CharField(max_length=300, verbose_name='Jina la Topic / Mada Kuu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='field_app.subject', verbose_name='Somo')),
            ],
            options={
                'verbose_name': 'Topic (Syllabus)',
                'verbose_name_plural': 'Topics (Syllabus)',
                'ordering': ['subject', 'class_name', 'order'],
                'unique_together': {('subject', 'class_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TopicSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Jina la Subtopic / Mada Ndogo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='curriculum.subjecttopic', verbose_name='Mada Kuu (Topic)')),
            ],
            options={
                'verbose_name': 'Subtopic (Syllabus)',
                'verbose_name_plural': 'Subtopics (Syllabus)',
                'ordering': ['topic', 'order'],
                'unique_together': {('topic', 'name')},
            },
        ),
    ]
