# Generated by Django 5.2.8 on 2026-08-10 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_add_preferred_language'),
        ('field_app', '0033_rename_computer_studies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmteacher',
            name='theme',
            field=models.CharField(choices=[('classic', 'TIE Classic — Navy & Gold'), ('tanzania', 'Tanzania — Green & Yellow'), ('ocean', 'Ocean Blue — Blue & Teal'), ('royal', 'Royal Purple — Purple & Pink'), ('executive', 'Executive — Charcoal & Silver'), ('sunset', 'Sunset — Warm Orange & Coral'), ('forest', 'Forest — Deep Green & Emerald'), ('midnight', 'Midnight — Dark Blue & Indigo'), ('cherry', 'Cherry — Red & Pink Blossom'), ('safari', 'Safari — Brown & Amber'), ('dawn', 'Dawn — Soft Pink & Lavender')], default='classic', help_text='Chagua rangi za PDF zako (Scheme & Lesson Plan)', max_length=20, verbose_name='Rangi / Theme'),
        ),
        migrations.CreateModel(
            name='GeneratedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Jina la Mtihani')),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('ordinary', 'Ordinary Level (O-Level)'), ('advanced', 'Advanced Level (A-Level)')], default='ordinary', max_length=20, verbose_name='Ngazi ya Elimu')),
                ('class_name', models.CharField(help_text='e.g. Form 2, Standard 5', max_length=50, verbose_name='Darasa')),
                ('subject_name', models.CharField(blank=True, max_length=200, verbose_name='Jina la Somo')),
                ('exam_type', models.CharField(choices=[('TEST', 'Test'), ('QUIZ', 'Quiz'), ('MIDTERM', 'Midterm'), ('TERMINAL', 'Terminal'), ('ANNUAL', 'Annual'), ('COMPETITION', 'Competition'), ('OTHER', 'Nyingine')], default='TEST', max_length=20, verbose_name='Aina ya Mtihani')),
                ('term', models.CharField(blank=True, default='', max_length=10, verbose_name='Muhula')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='Mwaka')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Muda (Dakika)')),
                ('total_marks', models.PositiveIntegerField(default=100, verbose_name='Alama Zote')),
                ('instructions', models.TextField(blank=True, verbose_name='Maagizo ya Jumla')),
                ('language', models.CharField(choices=[('english', 'English'), ('kiswahili', 'Kiswahili')], default='english', max_length=10, verbose_name='Lugha')),
                ('questions', models.JSONField(blank=True, default=list, verbose_name='Maswali')),
                ('topics_covered', models.JSONField(blank=True, default=list, verbose_name='Mada Zilizohusika')),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.school', verbose_name='Shule')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.subject', verbose_name='Somo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exams', to='curriculum.tlmteacher', verbose_name='Mwalimu (TLM)')),
            ],
            options={
                'verbose_name': 'Mtihani (Generated)',
                'verbose_name_plural': 'Mitihani (Generated)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TLMLogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day_of_week', models.CharField(choices=[('monday', 'Jumatatu'), ('tuesday', 'Jumanne'), ('wednesday', 'Jumatano'), ('thursday', 'Alhamisi'), ('friday', 'Ijumaa')], default='monday', max_length=10)),
                ('lessons_data', models.JSONField(blank=True, default=list)),
                ('other_activities', models.TextField(blank=True, null=True)),
                ('challenges_faced', models.TextField(blank=True, null=True)),
                ('lessons_learned', models.TextField(blank=True, null=True)),
                ('supervisor_remarks', models.TextField(blank=True, null=True)),
                ('head_teacher_remarks', models.TextField(blank=True, null=True)),
                ('is_location_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.school', verbose_name='Shule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='curriculum.tlmteacher', verbose_name='Mwalimu (TLM)')),
            ],
            options={
                'verbose_name': 'Logbook (TLM)',
                'verbose_name_plural': 'Logbooks (TLM)',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
