# Generated by Django 5.2.8 on 2026-08-12 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_lessonnote_technical_level'),
        ('field_app', '0035_textbook_technical_level_url_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLMTopicLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='Darasa')),
                ('term', models.CharField(blank=True, choices=[('I', 'Term I'), ('II', 'Term II'), ('III', 'Term III')], max_length=10, verbose_name='Term')),
                ('month', models.CharField(blank=True, max_length=20, verbose_name='Mwezi / Month')),
                ('week', models.CharField(blank=True, max_length=20, verbose_name='Wiki / Week')),
                ('main_topic', models.CharField(max_length=300, verbose_name='Mada Kuu / Main Topic')),
                ('subtopic', models.CharField(blank=True, max_length=300, verbose_name='Mada Ndogo / Subtopic')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Tarehe ya Kuanza / Date Started')),
                ('date_ended', models.DateField(default=django.utils.timezone.now, verbose_name='Tarehe ya Kumaliza / Date Ended')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Maoni ya Mwalimu wa Somo / Teacher Comment')),
                ('teacher_name', models.CharField(blank=True, max_length=200, verbose_name='Jina la Mwalimu (Sahihi)')),
                ('hod_comment', models.TextField(blank=True, verbose_name='Maoni ya Mkuu wa Idara / HOD Comment')),
                ('hod_name', models.CharField(blank=True, max_length=200, verbose_name='Jina la Mkuu wa Idara (Sahihi)')),
                ('head_comment', models.TextField(blank=True, verbose_name='Maelezo ya Mkuu wa Shule / Head of School Remarks')),
                ('head_name', models.CharField(blank=True, max_length=200, verbose_name='Jina la Mkuu wa Shule (Sahihi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_app.school', verbose_name='Shule')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_logbook_entries', to='field_app.subject', verbose_name='Somo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_logbook_entries', to='curriculum.tlmteacher', verbose_name='Mwalimu (TLM)')),
            ],
            options={
                'verbose_name': 'Subject Log-Book (kwa Topic)',
                'verbose_name_plural': 'Subject Log-Books (kwa Topic)',
                'ordering': ['-date_ended', '-created_at'],
            },
        ),
    ]
