# Generated by Django 5.2.8 on 2026-08-12 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_tlmtopiclogbook'),
        ('field_app', '0035_textbook_technical_level_url_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('ordinary', 'Ordinary Level'), ('advanced', 'Advanced Level'), ('technical', 'Technical / VETA')], max_length=20, verbose_name='Level')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='Darasa (mf. Form 4, Std 7)')),
                ('subject_name', models.CharField(blank=True, max_length=200, verbose_name='Jina la Somo (fallback)')),
                ('exam_code', models.CharField(blank=True, max_length=20, verbose_name='Mtihani (CSEE/FTNA/PSLE/ACSEE)')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Mwaka')),
                ('title', models.CharField(max_length=300, verbose_name='Jina la Past Paper')),
                ('url', models.URLField(verbose_name='Link ya PDF / Maktaba TETEA')),
                ('source', models.CharField(default='tetea', max_length=50, verbose_name='Chanzo')),
                ('marking_scheme_url', models.URLField(blank=True, verbose_name='Link ya Marking Scheme (hiari)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_papers', to='field_app.subject', verbose_name='Somo')),
            ],
            options={
                'verbose_name': 'Past Paper (NECTA)',
                'verbose_name_plural': 'Past Papers (NECTA)',
                'ordering': ['education_level', 'class_name', 'subject_name', '-year'],
            },
        ),
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=20, verbose_name='Level')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='Darasa')),
                ('subject_name', models.CharField(blank=True, max_length=200, verbose_name='Somo')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='Topic / Mada')),
                ('exam_code', models.CharField(blank=True, max_length=20, verbose_name='Mtihani')),
                ('content', models.TextField(verbose_name='Marking Scheme (maandishi/HTML)')),
                ('source', models.CharField(choices=[('ai', 'AI Generated'), ('link', 'External Link'), ('manual', 'Manual')], default='ai', max_length=20, verbose_name='Chanzo')),
                ('url', models.URLField(blank=True, verbose_name='Link ya nje (ikiwa source=link)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking_schemes', to=settings.AUTH_USER_MODEL, verbose_name='Iliyoundwa na')),
                ('past_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marking_schemes', to='curriculum.pastpaper', verbose_name='Past Paper')),
            ],
            options={
                'verbose_name': 'Marking Scheme',
                'verbose_name_plural': 'Marking Schemes',
                'ordering': ['-created_at'],
            },
        ),
    ]
