# Generated by Django 5.2.8 on 2026-08-11 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jina Kamili la Chuo')),
                ('short_name', models.CharField(help_text='Jina linalotumika kwenye namba ya usajili, mfano "KAS".', max_length=60, verbose_name='Jina Fupi (mf. Kasulu TC)')),
                ('code', models.CharField(help_text='Msimbo mfupi wa kipekee, mfano KAS (Kasulu), BUT (Butimba).', max_length=20, unique=True, verbose_name='Msimbo wa Chuo')),
                ('region', models.CharField(max_length=100, verbose_name='Mkoa')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Wilaya')),
                ('established', models.IntegerField(blank=True, null=True, verbose_name='Mwaka wa Kuanzishwa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Barua Pepe')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Namba ya Simu')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Anwani (P.O.Box)')),
                ('website', models.URLField(blank=True, verbose_name='Tovuti')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='college_logos/', verbose_name='Nembo (Logo)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Inatumika')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chuo',
                'verbose_name_plural': 'Vyuo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollegeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Jina Kamili')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Namba ya Simu')),
                ('title', models.CharField(blank=True, help_text='mfano: Mtumishi wa Mahesabu, Mkuu wa Chuo', max_length=100, verbose_name='Cheo')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='colleges.college', verbose_name='Chuo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Msimamizi wa Chuo',
                'verbose_name_plural': 'Wasimamizi wa Vyuo',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jina la Programu')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Msimbo wa Programu')),
                ('duration_years', models.IntegerField(default=2, verbose_name='Muda (Miaka)')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='colleges.college', verbose_name='Chuo')),
            ],
            options={
                'verbose_name': 'Programu',
                'verbose_name_plural': 'Programu',
                'ordering': ['name'],
            },
        ),
    ]
