# Generated by Django 5.2.8 on 2026-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='tuition_account_name',
            field=models.CharField(blank=True, help_text='Jina la mmiliki wa akaunti ya tuition.', max_length=150, verbose_name='Tuition Jina la Akaunti'),
        ),
        migrations.AddField(
            model_name='college',
            name='tuition_account_number',
            field=models.CharField(blank=True, help_text='Namba ya akaunti ya benki ya Tuition — inatofautiana kwa kila chuo.', max_length=30, verbose_name='Tuition Akaunti Namba'),
        ),
        migrations.AddField(
            model_name='college',
            name='tuition_bank_name',
            field=models.CharField(blank=True, help_text='mfano: NMB, CRDB, NBC', max_length=100, verbose_name='Tuition Benki (Jina la Benki)'),
        ),
    ]
