# Generated by Django 5.2.8 on 2026-08-11 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Jina Kamili')),
                ('registration_number', models.CharField(help_text='mfano: KAS/2026/014', max_length=50, unique=True, verbose_name='Namba ya Usajili')),
                ('admission_year', models.IntegerField(default=2026, verbose_name='Mwaka wa Kujiunga')),
                ('year_of_study', models.IntegerField(default=1, help_text='1 = Mwaka wa kwanza, 2 = Mwaka wa pili (Diploma = miaka 2)', verbose_name='Mwaka wa Masomo')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Mume (Male)'), ('F', 'Mke (Female)')], max_length=1, verbose_name='Jinsia')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Namba ya Simu')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Barua Pepe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='colleges.college', verbose_name='Chuo')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='colleges.program', verbose_name='Programu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Mwanafunzi',
                'verbose_name_plural': 'Wanafunzi',
                'ordering': ['full_name'],
            },
        ),
    ]
