# Generated by Django 5.2.8 on 2026-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Anasoma (Active)'), ('graduated', 'Alihitimu (Graduated)')], default='active', help_text='active = anasoma, graduated = alihitimu (bado anaweza kuwa na deni)', max_length=20, verbose_name='Hali ya Masomo'),
        ),
    ]
